name: build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      -- name: run install and build
        run: |
          npm install
          npm run build